#!/usr/bin/perl -w

$orest = "";
@opoints = ();

while (<>) {
	chomp;

	@points = ();
	while (s/^([0-9.-]+,[0-9.-]+) *//) {
		push @points, $1;
	}

	$rest = $_;

	if ($rest ne $orest || $points[0] ne $opoints[$#opoints]) {
		if ($#opoints >= 0) {
			for ($i = 0; $i <= $#opoints; $i++) {
				print "$opoints[$i] ";
			}
			print "$orest\n";
		}

		$orest = "";
		@opoints = ();
	} else {
		shift @points;
	}

	$orest = $rest;
	push @opoints, @points;
}

if ($#opoints >= 0) {
	if ($#opoints >= 0) {
		for ($i = 0; $i <= $#opoints; $i++) {
			print "$opoints[$i]";
		}
		print "$orest\n";
	}
}
