#!/usr/bin/perl

use POSIX;
use XML::Parser;

print "{\n\"type\": \"FeatureCollection\",\n\"features\": [\n";
$within = 0;
%coordinates = ();

sub handle_start {
	my ($expat, $element, @tags) = @_;
	my %tags = @tags;

	if ($element eq "trkpt") {
		$lat = $tags{'lat'};
		$lon = $tags{'lon'};
	} elsif ($element eq "ele") {
		$state = "ele";
	} elsif ($element eq "time") {
		$state = "time";
	} else {
		$state = "";
	}
}

sub handle_char {
	my ($expat, $s) = @_;
	$s =~ s/\n//g;
	if ($state eq "ele") {
		$ele .= $s;
	}
	if ($state eq "time") {
		$time .= $s;
	}
}

sub handle_end {
	my ($expat, $element) = @_;

	if ($element eq "trkseg" || $element eq "trk") {
		if ($#coordinates >= 0) {
			if ($within) {
				print ",\n";
			}
			$within = 1;

			print "{ \"type\": \"Feature\", \"properties\": { }, \"geometry\": { \"type\": \"LineString\", \"coordinates\": [ ";

			for ($i = 0; $i <= $#coordinates; $i++) {
				if ($i != 0) {
					print ", ";
				}
				my ($lon, $lat, $ele, $time) = split(/,/, $coordinates[$i]);
				print "[ $lon, $lat, $ele ]";
			}

			print "], \"attributes\": [ ";

			for ($i = 0; $i <= $#coordinates; $i++) {
				if ($i != 0) {
					print ", ";
				}
				my ($lon, $lat, $ele, $time) = split(/,/, $coordinates[$i]);
				print "{ \"time\": \"$time\" }";
			}

			print "] } }\n";
		}

		@coordinates = ();
	} elsif ($element eq "trkpt") {
		if ($lat ne "" && $lon ne "") {
			$ele =~ s/[ ,]*$//;
			$time =~ s/[ ,]*$//;
			$time =~ s/^[ ,]*//;

			push @coordinates, "$lon,$lat,$ele,$time";
		}

		$ele = "";
		$time = "";
	}
}

if ($#ARGV < 0) {
	$parser = new XML::Parser(Handlers => { Start => \&handle_start,
						End   => \&handle_end,
						Char  => \&handle_char,
					      });

	$parser->parse(*STDIN);
} else {
	for $file (@ARGV) {
		$oldwhen = 0;
		print STDERR "$file\n";

		$parser = new XML::Parser(Handlers => { Start => \&handle_start,
							End   => \&handle_end,
							Char  => \&handle_char,
						      });

		$parser->parsefile($file);
	}
}

print "]\n";
print "}\n";
